# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
#test12
name: EPE SERVER DOCKER PUSH
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "*"
        target: "/home/ubuntu/PEC/epeAdmin"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: /home/ubuntu/PEC/startDockerBuild.sh 
########################################
## FOR BOTH SSH COPY FILES ANDF DCOKKER# 
########################################
#name: EPE SERVER DOCKER PUSH
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#jobs:
#  build-epeAdmin:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    # - name: Build and Push Docker Image
#    #   uses: mr-smithers-excellent/docker-build-push@v5
#    #   with:
#    #     image: maliksblr92/cpdexam_epeserver
#    #     tags: v1, latest
#    #     registry: docker.io
#    #     username: ${{ secrets.DOCKER_USERNAME }}
#    #     password: ${{ secrets.DOCKER_PASSWORD }}
#  
#     uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.SSH_HOST }}
#        username: ${{ secrets.SSH_USERNAME }}
#        port: ${{ secrets.SSH_PORT }}
#        key: ${{ secrets.SSH_KEY }}
#        source: "*"
#        target: "/home/ubuntu/PEC/epeAdmin"
# 